---
- project:
    name: victorhugojt/recordtec-fe
    check:
      jobs:
        - recordtec-fe-check
        - recordtec-fe-lint
    gate:
      jobs:
        - recordtec-fe-check
        - recordtec-fe-lint